# Google Cloud Build Configuration
# Automatically builds and deploys to Cloud Run

steps:
  # Step 1: Build the application
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '--legacy-peer-deps']
    
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/solana-mev-bot:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/solana-mev-bot:latest'
      - '.'

  # Step 3: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/solana-mev-bot:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/solana-mev-bot:latest'

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'solana-mev-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/solana-mev-bot:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '3'
      - '--port'
      - '8080'
      - '--timeout'
      - '300'

images:
  - 'gcr.io/$PROJECT_ID/solana-mev-bot:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/solana-mev-bot:latest'

options:
  machineType: 'N1_HIGHCPU_8'
  timeout: '1200s'
